<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
=======
"use client"; // This must stay if the file uses client-only logic

import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";
import { CartProvider } from "use-shopping-cart";
import Header from "@/Components/Header";
>>>>>>> ac0e253 (Updated files)
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

<<<<<<< HEAD
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
=======
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider
          mode="payment"
          cartMode="client-only"
          stripe={process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY!}
          currency="USD"
          successUrl={`${process.env.NEXT_PUBLIC_BASE_URL}/success`}
          cancelUrl={`${process.env.NEXT_PUBLIC_BASE_URL}/cancel`}
          shouldPersist={true}
        >
          <Header />
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
>>>>>>> ac0e253 (Updated files)
      </body>
    </html>
  );
}
<<<<<<< HEAD
=======

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import React from "react";
// import "./globals.css";
// import { CartProvider } from "use-shopping-cart";
// import Header from "@/Components/Header";
// import Navbar from "@/Components/Navbar";
// import Footer from "@/Components/Footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <CartProvider
//       mode="payment"
//       cartMode="client-only"
//       currency="USD"
//       shouldPersist={true}
//       stripe={process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY || ""}
//       successUrl={`${process.env.NEXT_PUBLIC_BASE_URL}/success`}
//       cancelUrl={`${process.env.NEXT_PUBLIC_BASE_URL}/cancel`}

//     >
//       <html lang="en">
//         <body className={inter.className}>
//           <Header />
//           <Navbar />
//           <main>{children}</main>
//           <Footer />
//         </body>
//       </html>
//     </CartProvider>
//   );
// }
>>>>>>> ac0e253 (Updated files)
